"""
Django settings for miproyecto_SGE project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
# pymysql: el conector que instalaste en el paso 02
import pymysql
# Hace que Django use pymysql como si fuera el driver oficial de MySQL para Python
pymysql.install_as_MySQLdb()

# config: función de python-decouple que lee valores del archivo .env
from decouple import config

# Csv: convierte "a,b,c" del .env en la lista ['a','b','c']
from decouple import config, Csv

# se lee de .env (local) o del panel de Render (producción)
SECRET_KEY = config('SECRET_KEY')

# default=False: si falta la variable, queda apagado (lo seguro); cast=bool convierte "True"/"False" en booleano
DEBUG = config('DEBUG', default=False, cast=bool)

# dominios permitidos, separados por comas en la variable
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

# direcciones completas (con https://) desde las que se aceptan formularios, como el login de /admin
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*or63=+s(i-j2$rm@jufnu(spo*hh-=oo&)xod-@y@1-()#_rr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'core': tu app nueva, agregada al final de la lista
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoiseMiddleware: ← ESTA ES LA ÚNICA LÍNEA NUEVA; entrega los archivos CSS/JS/imágenes
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'miproyecto_SGE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'miproyecto_SGE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        # ENGINE: qué motor de base de datos usar — mysql en vez del sqlite3 por defecto
        'ENGINE': 'django.db.backends.mysql',
        # NAME: nombre de la base de datos, leído de la variable DB_NAME del .env
        'NAME': config('DB_NAME'),
        # USER: usuario de conexión, leído de DB_USER
        'USER': config('DB_USER'),
        # PASSWORD: contraseña de conexión, leída de DB_PASSWORD
        'PASSWORD': config('DB_PASSWORD'),
        # HOST: servidor donde vive la base de datos, leído de DB_HOST
        'HOST': config('DB_HOST'),
        # PORT: puerto de conexión; default='3306' se usa solo si DB_PORT no está en el .env
        'PORT': config('DB_PORT', default='3306'),
        # OPTIONS: Aiven exige que la conexión venga cifrada (SSL)
        'OPTIONS': {'ssl': {'ssl-mode': 'REQUIRED'}},
    # cierre del diccionario de configuración de la conexión
    }
# cierre del diccionario DATABASES
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT: NUEVO — carpeta "staticfiles" donde collectstatic junta TODOS los CSS/JS/imágenes del proyecto
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STORAGES: NUEVO — le dice a Django cómo guardar archivos
STORAGES = {
    # "default": archivos que suban los usuarios; se deja el sistema normal de Django (obligatorio declararlo)
    "default": {
        # FileSystemStorage: guarda en disco, igual que antes de este cambio
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    # cierre de la config de "default"
    },
    # "staticfiles": tus CSS/JS/imágenes; whitenoise los comprime y les pone una "huella" en el nombre
    "staticfiles": {
        # CompressedManifestStaticFilesStorage: el almacenamiento optimizado que trae whitenoise
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    # cierre de la config de "staticfiles"
    },
# cierre del diccionario STORAGES
}

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
